### ISSUE TITLE
Not working in Django 2.1

### ISSUE THREAD

**Issue by vaibhavhrt** [asaglimbeni/django-datetime-widget#109]
Works fine in 2.0.7 but in 2.1 it gives a Type error. "Django TypeError: render() got an unexpected keyword argument 'renderer'".

**Comment by vaibhavhrt** [comment]
I found the reason, https://docs.djangoproject.com/en/2.1/releases/2.1/#features-removed-in-2-1
Look at last removed feature.

**Comment by AgenticJamesBond** [comment]
Does that mean this package cannot move up to the next Django Version indefinitely?

**Comment by AgenticJamesBond** [comment]
#110 seems to have a solution,

**Comment by vaibhavhrt** [comment]
@Jaime5 I don't use this package anymore( I moved to React for frontend ) but still hope the owner merges the PR soon.
